apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: 422075260781.dkr.ecr.eu-west-2.amazonaws.com/swissding-client-app:latest
          imagePullPolicy: Always
          name: client
          ports:
            - containerPort: 4200
              protocol: TCP
