apiVersion: v1
kind: Service
metadata:
  annotations:
    description: {{ .Values.service_name }} http port
  labels:
    app: {{ .Values.service_name }}
    template: {{ .Values.service_name }}
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: web
      port: 4200
      protocol: TCP
      targetPort: 4200
      nodePort: 30040
  selector:
    app: {{ .Values.service_name }}
  type: NodePort
